/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/carteira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carteira */
        get: operations["carteira_carteira_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cotacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cotacoes
         * @description Cotação mais recente de cada ativo cadastrado — inclusive os SEM
         *     cotação, representados explicitamente em vez de omitidos.
         */
        get: operations["cotacoes_cotacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sugestoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sugestoes */
        get: operations["sugestoes_sugestoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desfecho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desfecho
         * @description Desfecho da execução mais recente do dia — por que (não) saiu
         *     sugestão. Lê o registro que a avaliação gravou; NÃO roda a avaliação.
         */
        get: operations["desfecho_desfecho_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CarteiraResposta */
        CarteiraResposta: {
            /** Posicoes */
            posicoes: components["schemas"]["PosicaoResposta"][];
            /** Total Patrimonio */
            total_patrimonio: number;
            /**
             * Patrimonio Parcial
             * @description True quando alguma posição ficou sem cotação utilizável — o total NÃO cobre a carteira inteira
             */
            patrimonio_parcial: boolean;
            /** Tickers Sem Cotacao */
            tickers_sem_cotacao: string[];
            /** Motivos Sem Cotacao */
            motivos_sem_cotacao: string[];
            /** Exposicao Pct Por Ativo */
            exposicao_pct_por_ativo: {
                [key: string]: number;
            };
        };
        /** CotacaoResposta */
        CotacaoResposta: {
            /** Ticker */
            ticker: string;
            /** Preco */
            preco: number | null;
            /** Coletado Em */
            coletado_em: string | null;
            /** Tem Cotacao */
            tem_cotacao: boolean;
        };
        /** DesfechoResposta */
        DesfechoResposta: {
            /**
             * Executado Em
             * @description Momento da avaliação que produziu este desfecho — se ela não rodou hoje, é de outro dia
             */
            executado_em: string | null;
            /** Ha Registro */
            ha_registro: boolean;
            /** Motivos */
            motivos: components["schemas"]["MotivoDesfechoResposta"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MotivoDesfechoResposta */
        MotivoDesfechoResposta: {
            /** Ticker Objeto */
            ticker_objeto: string;
            /** Motivo */
            motivo: string;
            /** Quantidade */
            quantidade: number;
            /**
             * Criterios Contagem
             * @description A soma PODE exceder `quantidade`: opção reprovada em dois critérios conta nos dois
             */
            criterios_contagem: {
                [key: string]: number;
            };
            /** Amostra */
            amostra: {
                [key: string]: unknown;
            } | null;
        };
        /** PosicaoResposta */
        PosicaoResposta: {
            /** Ticker */
            ticker: string;
            /** Tipo Ativo */
            tipo_ativo: string;
            /** Quantidade */
            quantidade: number;
            /**
             * Preco Medio
             * @description Base de custo — nunca usada como valor
             */
            preco_medio: number;
            /** Preco Mercado */
            preco_mercado: number | null;
            /** Cotacao Em */
            cotacao_em: string | null;
            /** Motivo Sem Cotacao */
            motivo_sem_cotacao: string | null;
            /** Valor */
            valor: number | null;
        };
        /** SugestaoResposta */
        SugestaoResposta: {
            /** Ticker Objeto */
            ticker_objeto: string;
            /** Tipo Operacao */
            tipo_operacao: string;
            /** Codigo Opcao */
            codigo_opcao: string | null;
            /** Strike */
            strike: number | null;
            /** Vencimento */
            vencimento: string | null;
            /** Premio Estimado */
            premio_estimado: number | null;
            /** Status */
            status: string;
            /**
             * Criterios
             * @description Snapshot completo, com a base de valorização
             */
            criterios: {
                [key: string]: unknown;
            };
            /**
             * Pendente Revisao Humana
             * @description Sempre True: nenhuma sugestão é ordem executada
             */
            pendente_revisao_humana: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    carteira_carteira_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarteiraResposta"];
                };
            };
        };
    };
    cotacoes_cotacoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CotacaoResposta"][];
                };
            };
        };
    };
    sugestoes_sugestoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SugestaoResposta"][];
                };
            };
        };
    };
    desfecho_desfecho_get: {
        parameters: {
            query?: {
                data?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesfechoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
