/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ativos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Ativos
         * @description Ativos cadastrados — o pré-requisito de todo o resto.
         *
         *     `cotacoes`, `opcoes` e `noticias` têm FK para `ativos`: sem cadastro, o
         *     ETL recusa o ticker e registrar posição em ação falha.
         */
        get: operations["listar_ativos_ativos_get"];
        put?: never;
        /**
         * Cadastrar Ativo
         * @description Cadastra ou CORRIGE um ativo.
         *
         *     Regravar o mesmo ticker atualiza a linha em vez de duplicar ou falhar —
         *     as cotações já coletadas continuam associadas, porque a chave primária
         *     não muda.
         */
        post: operations["cadastrar_ativo_ativos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posicoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Posicoes
         * @description Posições em aberto (`fechada_em IS NULL`).
         */
        get: operations["listar_posicoes_posicoes_get"];
        put?: never;
        /**
         * Registrar Posicao
         * @description Registra uma posição que o usuário JÁ tem.
         *
         *     Isto é escrituração, não ordem: o sistema não fala com corretora em
         *     lugar nenhum. Quantidade negativa registra posição lançada — o caso da
         *     venda coberta.
         */
        post: operations["registrar_posicao_posicoes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posicoes/{posicao_id}/encerrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerrar Posicao
         * @description Marca `fechada_em` com o desfecho. A linha NUNCA é removida: o
         *     histórico é o que permite explicar uma decisão passada meses depois.
         *
         *     Exige corpo com o motivo — o que também serve de confirmação: encerrar
         *     é irreversível pela interface (não existe reabrir), e um POST vazio
         *     tornava perda de dado a um clique de distância.
         */
        post: operations["encerrar_posicao_posicoes__posicao_id__encerrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Watchlist
         * @description Ativos vigiados e o custo que isso impõe ao orçamento diário.
         */
        get: operations["listar_watchlist_watchlist_get"];
        put?: never;
        /**
         * Adicionar A Watchlist
         * @description Passa a vigiar um ativo JÁ CADASTRADO.
         *
         *     Vigiar não cadastra: `ativos` é alvo de FK de cotação, opção e notícia,
         *     e criar o registro aqui exigiria inventar o nome do ativo — o que a
         *     regra 1 do projeto proíbe.
         */
        post: operations["adicionar_a_watchlist_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{ticker}/remover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remover Da Watchlist
         * @description Sai da varredura e para de consumir orçamento. O cadastro e o
         *     histórico permanecem — isto não descadastra o ativo.
         */
        post: operations["remover_da_watchlist_watchlist__ticker__remover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/caixa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ler Caixa */
        get: operations["ler_caixa_caixa_get"];
        put?: never;
        /**
         * Lancar Caixa
         * @description Registra um lançamento. É o que torna uma PUT coberta, coberta:
         *     sem garantia para honrar o exercício ao strike, `avaliar()` recusa a
         *     operação em vez de tratá-la como coberta.
         */
        post: operations["lancar_caixa_caixa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar No Catalogo
         * @description Procura ativos por código ou nome no catálogo do provedor.
         *
         *     Existe para o cadastro não depender de digitação: nome e CNPJ vêm da
         *     fonte em vez da memória do usuário. Um dígito trocado no CNPJ raiz
         *     quebra o vínculo com o dump da CVM, e o calendário de resultados fica
         *     silenciosamente vazio para aquele ativo.
         *
         *     Cada chamada consome 1 request do orçamento diário — a interface deve
         *     buscar no envio, nunca a cada tecla.
         */
        get: operations["buscar_no_catalogo_catalogo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalogo/{ticker}/cnpj": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cnpj Do Catalogo
         * @description Raiz do CNPJ do ativo, para preencher o vínculo com a CVM.
         */
        get: operations["cnpj_do_catalogo_catalogo__ticker__cnpj_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carteira": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carteira */
        get: operations["carteira_carteira_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cotacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cotacoes
         * @description Cotação mais recente de cada ativo cadastrado — inclusive os SEM
         *     cotação, representados explicitamente em vez de omitidos.
         */
        get: operations["cotacoes_cotacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sugestoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sugestoes */
        get: operations["sugestoes_sugestoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/desfecho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Desfecho
         * @description Desfecho da execução mais recente do dia — por que (não) saiu
         *     sugestão. Lê o registro que a avaliação gravou; NÃO roda a avaliação.
         */
        get: operations["desfecho_desfecho_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resultados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resultados
         * @description Calendário de divulgação de resultado por ativo.
         *
         *     Duas coisas que este endpoint não faz, de propósito: não roda o
         *     `ingest` (a API não dispara) e não decide se a data é boa o bastante —
         *     quem faz isso é `EarningsRiskService`. Aqui se expõe o estado como ele
         *     está no banco, inclusive quando esse estado é "o usuário registrou e
         *     ninguém consolidou".
         */
        get: operations["resultados_resultados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude-coleta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saude Coleta
         * @description Quando cada fonte entregou dado pela última vez, e quanto do
         *     orçamento diário de requests já foi gasto.
         *
         *     NÃO é um log de execução — o projeto não grava tentativa, erro nem
         *     duração em lugar nenhum. Por isso a resposta carrega
         *     `rastreia_falhas=False`: ausência de entrega recente aqui significa
         *     "não gravou nada", que pode ser fonte quebrada ou simplesmente dia sem
         *     novidade, e o banco não sabe qual dos dois.
         */
        get: operations["saude_coleta_saude_coleta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles
         * @description Velas OHLC de um ticker, mais antigas primeiro.
         *
         *     O corte por `limite` é feito pelas MAIS RECENTES (ORDER BY DESC no
         *     subselect) e só depois reordenado para o desenho: pedir 200 velas de uma
         *     série de 5.000 precisa devolver as 200 últimas, não as 200 primeiras.
         */
        get: operations["candles_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operacoes
         * @description Operações de opção — abertas e encerradas — com resultado estimado.
         *
         *     NÃO há marcação a mercado da opção: o ETL de opções está bloqueado no
         *     plano Free do provedor e `opcoes` fica vazia. O que se usa é a cotação
         *     do ATIVO-OBJETO, que responde a pergunta central da venda coberta ("a
         *     ação passou do strike?") sem precisar do preço da opção. A resposta
         *     declara esse limite em `tem_cotacao_de_opcao`.
         */
        get: operations["operacoes_operacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enriquecimento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Enriquecimento
         * @description Contexto quantitativo da última execução da avaliação.
         *
         *     Uma execução por vez, não a união do dia: rodar de novo SUBSTITUI a
         *     leitura. Somar rodadas mostraria a mesma opção duas vezes com números
         *     ligeiramente diferentes, e ninguém saberia qual é a de agora — é a mesma
         *     razão de `ultima_execucao_do_dia` existir no desfecho.
         */
        get: operations["enriquecimento_enriquecimento_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parametros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parametros
         * @description Os parâmetros de `params.yaml` que a interface precisa citar.
         *
         *     Sem isto a interface duplicaria a janela de frescor e a política de
         *     resultado desconhecido — e passaria a mentir em silêncio no dia em que
         *     esses valores mudassem aqui.
         */
        get: operations["parametros_parametros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AtivoEntrada */
        AtivoEntrada: {
            /** Ticker */
            ticker: string;
            /**
             * Nome
             * @description Obrigatório: o sistema NUNCA deriva nome a partir do ticker
             */
            nome: string;
            /**
             * Tipo
             * @description acao | fii | bdr
             * @default acao
             */
            tipo: string;
            /**
             * Cnpj Raiz
             * @description 8 dígitos, a RAIZ do CNPJ — é o que liga o ativo ao dump da CVM para datas de resultado
             */
            cnpj_raiz?: string | null;
        };
        /** AtivoResposta */
        AtivoResposta: {
            /** Ticker */
            ticker: string;
            /** Nome */
            nome: string;
            /** Tipo */
            tipo: string;
            /** Cnpj Raiz */
            cnpj_raiz: string | null;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /**
         * AutomacaoResposta
         * @description Execução automática do pipeline — o que `rastreia_falhas` não cobre.
         *
         *     Diferente das coletas acima, aqui a falha É registrada: cada disparo grava
         *     uma linha antes de começar e a fecha com o desfecho. É o que permite
         *     distinguir "pulou porque não era pregão" de "quebrou" de "nunca rodou".
         */
        AutomacaoResposta: {
            /**
             * Disponivel
             * @description False quando a migração 007 não foi aplicada neste banco
             */
            disponivel: boolean;
            /** Rodou Hoje */
            rodou_hoje: boolean;
            ultima?: components["schemas"]["ExecucaoResposta"] | null;
            /** Recentes */
            recentes?: components["schemas"]["ExecucaoResposta"][];
            /**
             * Interrompidas
             * @description Abertas há mais de uma hora e nunca encerradas: processos mortos no meio (OOM, kill, máquina desligada)
             */
            interrompidas?: components["schemas"]["ExecucaoResposta"][];
            calendario?: components["schemas"]["CalendarioPregaoResposta"] | null;
        };
        /** CaixaEntrada */
        CaixaEntrada: {
            /**
             * Valor
             * @description Positivo aporta, negativo retira. Zero é recusado
             */
            valor: number;
            /** Descricao */
            descricao?: string | null;
        };
        /**
         * CaixaResposta
         * @description Saldo e extrato.
         *
         *     O saldo é a SOMA dos lançamentos, nunca um número sobrescrito: é o
         *     "como se chegou até aqui" que explica, meses depois, por que uma
         *     avaliação aceitou ou recusou uma put.
         */
        CaixaResposta: {
            /** Saldo */
            saldo: number;
            /**
             * Garante Put
             * @description False quando o saldo é zero — e é isso que faz `avaliar()` recusar a put como não coberta
             */
            garante_put: boolean;
            /** Lancamentos */
            lancamentos: components["schemas"]["LancamentoResposta"][];
        };
        /**
         * CalendarioPregaoResposta
         * @description Estado do calendário que decide se há pregão.
         *
         *     `anos_derivados` existe porque derivado não pode passar por conferido: as
         *     datas funcionam, mas não foram batidas contra a fonte oficial — a mesma
         *     distinção que `earnings` faz entre estimado e confirmado.
         */
        CalendarioPregaoResposta: {
            /**
             * Vigencia De
             * Format: date
             */
            vigencia_de: string;
            /**
             * Vigencia Ate
             * Format: date
             */
            vigencia_ate: string;
            /** Conferido Em */
            conferido_em: string | null;
            /** Anos Conferidos */
            anos_conferidos: number[];
            /** Anos Derivados */
            anos_derivados: number[];
            /** Fonte */
            fonte: string;
            /**
             * Erro
             * @description Preenchido quando o arquivo não pôde ser lido. Nesse estado NENHUM disparo roda: sem calendário não há como distinguir dia útil de feriado
             */
            erro?: string | null;
        };
        /** CanalColetaResposta */
        CanalColetaResposta: {
            /**
             * Canal
             * @description O que é coletado: cotações, opções, notícias, resultados
             */
            canal: string;
            /** Fonte */
            fonte: string;
            /**
             * Ultima Entrega Em
             * @description Última vez que esta fonte GRAVOU dado. Não é 'última tentativa': uma falha não deixa rastro no banco
             */
            ultima_entrega_em: string | null;
            /** Registros Hoje */
            registros_hoje: number;
            /** Ja Entregou */
            ja_entregou: boolean;
        };
        /**
         * CandidatoResposta
         * @description Um ativo do catálogo do provedor, já avaliado quanto ao cadastro.
         *
         *     `impedimentos` não vazio significa que o candidato aparece mas NÃO pode
         *     ser cadastrado como está — com o motivo, para não sumir sem explicação
         *     e o usuário procurar de novo pelo mesmo ticker.
         */
        CandidatoResposta: {
            /** Ticker */
            ticker: string;
            /**
             * Nome
             * @description `null` quando a fonte devolve o próprio ticker como nome (BDR e fundos) — assumir seria derivar nome do ticker, que a regra 1 do projeto proíbe
             */
            nome: string | null;
            /** Tipo */
            tipo: string | null;
            /** Setor */
            setor: string | null;
            /** Impedimentos */
            impedimentos: string[];
            /** Cadastravel */
            cadastravel: boolean;
        };
        /**
         * CandlesResposta
         * @description Série de velas de um ticker, em ordem cronológica.
         *
         *     `intervalo` volta na resposta de propósito: é o que permite a interface
         *     desenhar o eixo correto sem supor a granularidade. Trocar o ETL para
         *     coletar 15m passa a refletir aqui sem mudança no contrato.
         */
        CandlesResposta: {
            /** Ticker */
            ticker: string;
            /** Intervalo */
            intervalo: string;
            /** Velas */
            velas: components["schemas"]["VelaResposta"][];
            /**
             * Intervalos Disponiveis
             * @description Intervalos que já têm vela gravada para este ticker
             */
            intervalos_disponiveis: string[];
        };
        /** CarteiraResposta */
        CarteiraResposta: {
            /** Posicoes */
            posicoes: components["schemas"]["PosicaoResposta"][];
            /** Total Patrimonio */
            total_patrimonio: number;
            /**
             * Patrimonio Parcial
             * @description True quando alguma posição ficou sem cotação utilizável — o total NÃO cobre a carteira inteira
             */
            patrimonio_parcial: boolean;
            /** Tickers Sem Cotacao */
            tickers_sem_cotacao: string[];
            /** Motivos Sem Cotacao */
            motivos_sem_cotacao: string[];
            /** Exposicao Pct Por Ativo */
            exposicao_pct_por_ativo: {
                [key: string]: number;
            };
        };
        /**
         * CenarioResposta
         * @description Desfecho hipotético de uma operação AINDA ABERTA.
         *
         *     Não é previsão de preço: é aritmética sobre o que aconteceria se a
         *     opção terminasse de cada jeito, com os números que já existem.
         */
        CenarioResposta: {
            /** Nome */
            nome: string;
            /** Descricao */
            descricao: string;
            /** Resultado Liquido */
            resultado_liquido: number;
        };
        /** CotacaoResposta */
        CotacaoResposta: {
            /** Ticker */
            ticker: string;
            /** Preco */
            preco: number | null;
            /** Coletado Em */
            coletado_em: string | null;
            /** Tem Cotacao */
            tem_cotacao: boolean;
        };
        /** DesfechoResposta */
        DesfechoResposta: {
            /**
             * Executado Em
             * @description Momento da avaliação que produziu este desfecho — se ela não rodou hoje, é de outro dia
             */
            executado_em: string | null;
            /** Ha Registro */
            ha_registro: boolean;
            /** Motivos */
            motivos: components["schemas"]["MotivoDesfechoResposta"][];
        };
        /**
         * EncerramentoEntrada
         * @description Como a posição fechou — obrigatório porque o resultado depende disso.
         *
         *     `fechada_em` sozinho diz QUANDO fechou e nunca COMO: expirada rende o
         *     prêmio inteiro, recomprada rende o prêmio menos a recompra, exercida
         *     atravessa duas categorias fiscais.
         */
        EncerramentoEntrada: {
            /**
             * Motivo
             * @description expirada | recomprada | exercida | encerrada
             * @default encerrada
             */
            motivo: string;
            /**
             * Preco Fechamento
             * @description Obrigatório em `recomprada`: é o que se pagou para sair. Sem ele o resultado sairia superestimado
             */
            preco_fechamento?: number | null;
        };
        /**
         * EnriquecimentoItemResposta
         * @description Contexto quantitativo de UMA opção. Todo número é opcional: `None`
         *     quer dizer "não deu para calcular", e `ressalvas` diz por quê.
         */
        EnriquecimentoItemResposta: {
            /** Codigo Opcao */
            codigo_opcao: string;
            /** Ticker Objeto */
            ticker_objeto: string;
            /** Tipo */
            tipo?: string | null;
            /** Strike */
            strike?: number | null;
            /** Vencimento */
            vencimento?: string | null;
            /** Preco Mercado */
            preco_mercado?: number | null;
            /** Preco Teorico */
            preco_teorico?: number | null;
            /**
             * Delta Modelo
             * @description Delta do MODELO. Não confundir com `opcoes.delta`, que vem do provedor e é o que o critério de gate consome
             */
            delta_modelo?: number | null;
            /** Gamma */
            gamma?: number | null;
            /**
             * Theta Dia
             * @description Por dia corrido
             */
            theta_dia?: number | null;
            /**
             * Vega Pp
             * @description Por ponto percentual de vol
             */
            vega_pp?: number | null;
            /**
             * Rho Pp
             * @description Por ponto percentual de juro
             */
            rho_pp?: number | null;
            /**
             * Prob Exercicio Vencimento
             * @description Risco-neutra, SÓ no vencimento — não inclui exercício antecipado em contrato americano
             */
            prob_exercicio_vencimento?: number | null;
            /** Iv Percentil 252D */
            iv_percentil_252d?: number | null;
            /** Skew Vs Cadeia */
            skew_vs_cadeia?: number | null;
            /** Volatilidade Usada */
            volatilidade_usada?: number | null;
            /** Estilo Exercicio */
            estilo_exercicio?: string | null;
            /** Ressalvas */
            ressalvas?: string[];
        };
        /**
         * EnriquecimentoResposta
         * @description Contexto quantitativo da última execução da avaliação.
         *
         *     NÃO é critério. Os números aqui não aprovaram nem reprovaram nada — quem
         *     decide é `criterios_json`, em `/sugestoes` e `/desfecho`. A separação é a
         *     razão de existir um recurso próprio: misturar os dois faria um número de
         *     contexto parecer um critério que alguém precisou passar.
         */
        EnriquecimentoResposta: {
            /**
             * Disponivel
             * @description False quando a migração 008 não foi aplicada neste banco
             */
            disponivel: boolean;
            /** Executado Em */
            executado_em?: string | null;
            /**
             * Modelo
             * @description Ex.: 'CRR-binomial-1024'
             */
            modelo?: string | null;
            /**
             * Taxa Livre Risco
             * @description Fração ao ano usada no desconto
             */
            taxa_livre_risco?: number | null;
            /** Taxa Observada Em */
            taxa_observada_em?: string | null;
            /** Itens */
            itens?: components["schemas"]["EnriquecimentoItemResposta"][];
        };
        /** EventoResultadoResposta */
        EventoResultadoResposta: {
            /** Ticker */
            ticker: string;
            /** Empresa */
            empresa: string | null;
            /** Periodo Fiscal */
            periodo_fiscal: string;
            /**
             * Data Efetiva
             * @description A confirmada quando existe, senão a estimada — é esta que o motor de opções consulta
             */
            data_efetiva: string | null;
            /** Data Estimada */
            data_estimada: string | null;
            /**
             * Data Confirmada
             * @description Coluna separada da estimada de propósito: manter as duas preserva a discordância em vez de apagá-la
             */
            data_confirmada: string | null;
            /** Hora Efetiva */
            hora_efetiva: string | null;
            /**
             * Sessao
             * @description UNKNOWN não é ausência a ignorar — é estado que AMPLIA a janela de risco
             */
            sessao: string;
            /** Status */
            status: string;
            /** Confianca */
            confianca: number;
            /** Faixa Confianca */
            faixa_confianca: string;
            /** Confirmado */
            confirmado: boolean;
            /**
             * Conflitos
             * @description Divergências entre fontes, preservadas em vez de resolvidas em silêncio
             */
            conflitos: unknown[];
            /**
             * Atualizado Em
             * Format: date-time
             */
            atualizado_em: string;
            /** Fontes */
            fontes: components["schemas"]["FonteResultadoResposta"][];
        };
        /**
         * ExecucaoResposta
         * @description Um disparo do pipeline de pregão (`execucao_pipeline`, migração 007).
         */
        ExecucaoResposta: {
            /** Id */
            id: number;
            /**
             * Iniciado Em
             * Format: date-time
             */
            iniciado_em: string;
            /**
             * Encerrado Em
             * @description NULL com status='executando' é o rastro de um processo que morreu no meio — a linha abre ANTES do trabalho
             */
            encerrado_em?: string | null;
            /**
             * Status
             * @description executando | executado | pulado_fora_de_pregao | falhou
             */
            status: string;
            /** Gatilho */
            gatilho: string;
            /** Duracao S */
            duracao_s?: number | null;
            /**
             * Detalhe
             * @description Resumo por etapa: janela, orçamento, avaliação; erro e traceback quando o status é 'falhou'
             */
            detalhe?: {
                [key: string]: unknown;
            };
        };
        /**
         * FonteResultadoResposta
         * @description O que UMA fonte afirmou sobre a data, preservado como veio.
         *
         *     Linhas perdedoras de um conflito continuam aqui: são o rastro que
         *     responde "por que o sistema achava isso?" meses depois.
         */
        FonteResultadoResposta: {
            /** Provedor */
            provedor: string;
            /** Data Reportada */
            data_reportada: string | null;
            /** Status */
            status: string | null;
            /** Confianca */
            confianca: number;
            /**
             * Obtida Em
             * Format: date-time
             */
            obtida_em: string;
            /** Url */
            url: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LancamentoResposta */
        LancamentoResposta: {
            /** Id */
            id: number;
            /** Valor */
            valor: number;
            /** Descricao */
            descricao: string | null;
            /**
             * Ocorrido Em
             * Format: date-time
             */
            ocorrido_em: string;
        };
        /** MotivoDesfechoResposta */
        MotivoDesfechoResposta: {
            /** Ticker Objeto */
            ticker_objeto: string;
            /** Motivo */
            motivo: string;
            /** Quantidade */
            quantidade: number;
            /**
             * Criterios Contagem
             * @description A soma PODE exceder `quantidade`: opção reprovada em dois critérios conta nos dois
             */
            criterios_contagem: {
                [key: string]: number;
            };
            /** Amostra */
            amostra: {
                [key: string]: unknown;
            } | null;
        };
        /** OperacaoResposta */
        OperacaoResposta: {
            /** Posicao Id */
            posicao_id: number;
            /** Codigo */
            codigo: string;
            /** Ticker Objeto */
            ticker_objeto: string | null;
            /**
             * Quantidade
             * @description Negativo = lançada. Em opções, não contratos
             */
            quantidade: number;
            /** Premio Unitario */
            premio_unitario: number;
            /** Strike */
            strike: number | null;
            /** Vencimento */
            vencimento: string | null;
            /** Dias Para Vencimento */
            dias_para_vencimento: number | null;
            /**
             * Aberta Em
             * Format: date-time
             */
            aberta_em: string;
            /** Fechada Em */
            fechada_em: string | null;
            /** Motivo Fechamento */
            motivo_fechamento: string | null;
            /** Preco Fechamento */
            preco_fechamento: number | null;
            /** Preco Objeto */
            preco_objeto: number | null;
            /**
             * Distancia Do Strike Pct
             * @description Quanto o objeto está acima (+) ou abaixo (−) do strike. É a pergunta central da venda coberta
             */
            distancia_do_strike_pct: number | null;
            /** Dentro Do Dinheiro */
            dentro_do_dinheiro: boolean | null;
            /** Resultado Bruto */
            resultado_bruto: number;
            /** Custos */
            custos: number;
            /** Imposto */
            imposto: number;
            /** Resultado Liquido */
            resultado_liquido: number;
            /** Pernas */
            pernas: components["schemas"]["PernaResposta"][];
            /** Cenarios */
            cenarios: components["schemas"]["CenarioResposta"][];
            /**
             * Estimativa
             * @description Sempre True: é estimativa por operação, não apuração fiscal — a real é mensal e consolida operações
             * @default true
             */
            estimativa: boolean;
            /** Ressalvas */
            ressalvas: string[];
        };
        /** OperacoesResposta */
        OperacoesResposta: {
            /** Operacoes */
            operacoes: components["schemas"]["OperacaoResposta"][];
            /**
             * Tem Cotacao De Opcao
             * @description False enquanto o ETL de opções estiver bloqueado: sem ele não há marcação a mercado da posição em opção
             */
            tem_cotacao_de_opcao: boolean;
        };
        /** OrcamentoResposta */
        OrcamentoResposta: {
            /** Fonte */
            fonte: string;
            /** Limite Diario */
            limite_diario: number;
            /** Gastos Hoje */
            gastos_hoje: number;
            /** Restante Hoje */
            restante_hoje: number;
            /**
             * E Aproximacao
             * @description Sempre True: não há tabela de contagem de requests. O gasto é estimado pelas linhas gravadas hoje, o que SUBESTIMA quando um request falha antes de gravar
             * @default true
             */
            e_aproximacao: boolean;
        };
        /**
         * ParametrosResposta
         * @description Parâmetros de `params.yaml` que a interface precisa para explicar o
         *     que mostra.
         *
         *     Existem no contrato porque a alternativa é a interface duplicar os
         *     números e passar a mentir em silêncio quando eles mudarem aqui.
         */
        ParametrosResposta: {
            /**
             * Cotacao Frescor Maximo Horas
             * @description Idade máxima da cotação para valer como preço de mercado. Passou disso, a avaliação para como 'dado insuficiente' — não existe fallback para preço médio
             */
            cotacao_frescor_maximo_horas: number;
            /** Politica Resultado Desconhecido */
            politica_resultado_desconhecido: string;
        };
        /**
         * PendenteConsolidacaoResposta
         * @description Data que o usuário registrou e que NUNCA virou evento consultável.
         *
         *     Registrar não é consolidar: `earnings.manage add` grava o que o usuário
         *     leu no site de RI, e só `earnings.ingest` promove aquilo para
         *     `earnings_events`. Sem o segundo passo a data existe no banco e a
         *     avaliação segue bloqueada — a armadilha mais cara deste fluxo, e por
         *     isso ela é exposta como estado próprio em vez de ficar invisível.
         */
        PendenteConsolidacaoResposta: {
            /** Ticker */
            ticker: string;
            /** Periodo Fiscal */
            periodo_fiscal: string;
            /**
             * Data Resultado
             * Format: date
             */
            data_resultado: string;
            /** Sessao */
            sessao: string;
            /** Origem */
            origem: string | null;
            /**
             * Registrado Em
             * Format: date-time
             */
            registrado_em: string;
            /**
             * Comando Para Consolidar
             * @description O comando exato que promove esta entrada a evento
             */
            comando_para_consolidar: string;
        };
        /** PernaResposta */
        PernaResposta: {
            /** Nome */
            nome: string;
            /** Resultado Bruto */
            resultado_bruto: number;
            /** Custos */
            custos: number;
            /** Aliquota Pct */
            aliquota_pct: number;
            /** Imposto */
            imposto: number;
            /** Resultado Liquido */
            resultado_liquido: number;
        };
        /** PosicaoAbertaResposta */
        PosicaoAbertaResposta: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Tipo Ativo */
            tipo_ativo: string;
            /** Quantidade */
            quantidade: number;
            /** Preco Medio */
            preco_medio: number;
            /**
             * Aberta Em
             * Format: date-time
             */
            aberta_em: string;
            /** Origem */
            origem: string;
        };
        /** PosicaoCriada */
        PosicaoCriada: {
            /** Id */
            id: number;
            /**
             * Executou Ordem
             * @description Sempre False. Registrar posição é espelhar o que já existe na corretora; nada foi enviado a lugar nenhum
             * @default false
             */
            executou_ordem: boolean;
        };
        /** PosicaoEntrada */
        PosicaoEntrada: {
            /**
             * Ticker
             * @description Em ACAO é o ticker do ativo (precisa estar cadastrado); em OPCAO é o CÓDIGO da opção, que não é linha em `ativos`
             */
            ticker: string;
            /**
             * Tipo Ativo
             * @description ACAO | OPCAO
             */
            tipo_ativo: string;
            /**
             * Quantidade
             * @description Negativo = posição LANÇADA (vendida). É assim que uma venda coberta é registrada. Está em OPÇÕES (cada uma sobre 1 ação), não em contratos
             */
            quantidade: number;
            /**
             * Preco Medio
             * @description Base de custo — nunca valor de mercado
             */
            preco_medio: number;
            /**
             * Ticker Objeto
             * @description A ação que a opção cobre. Informado, não inferido: derivar do código exigiria interpretar código B3
             */
            ticker_objeto?: string | null;
            /** Strike */
            strike?: number | null;
            /** Vencimento */
            vencimento?: string | null;
        };
        /** PosicaoResposta */
        PosicaoResposta: {
            /** Ticker */
            ticker: string;
            /** Tipo Ativo */
            tipo_ativo: string;
            /** Quantidade */
            quantidade: number;
            /**
             * Preco Medio
             * @description Base de custo — nunca usada como valor
             */
            preco_medio: number;
            /** Preco Mercado */
            preco_mercado: number | null;
            /** Cotacao Em */
            cotacao_em: string | null;
            /** Motivo Sem Cotacao */
            motivo_sem_cotacao: string | null;
            /** Valor */
            valor: number | null;
        };
        /** ResultadosResposta */
        ResultadosResposta: {
            /** Eventos */
            eventos: components["schemas"]["EventoResultadoResposta"][];
            /** Pendentes Consolidacao */
            pendentes_consolidacao: components["schemas"]["PendenteConsolidacaoResposta"][];
            /**
             * Politica Resultado Desconhecido
             * @description O que a avaliação faz sem data confiável: `bloquear` (padrão, conservador) ou `sinalizar`. Reprovação em critério de mercado sempre vence a política
             */
            politica_resultado_desconhecido: string;
        };
        /**
         * SaudeColetaResposta
         * @description Saúde da coleta, derivada do dado que já existe.
         *
         *     Para as COLETAS este recurso não é um log: o projeto não grava tentativa
         *     nem erro por fonte, então ele responde "quando cada fonte entregou dado
         *     pela última vez", que é o que o banco sabe. Para a EXECUÇÃO do pipeline
         *     de pregão, `automacao` é um log de verdade — ver `AutomacaoResposta`.
         */
        SaudeColetaResposta: {
            /** Coletas */
            coletas: components["schemas"]["CanalColetaResposta"][];
            orcamento: components["schemas"]["OrcamentoResposta"];
            /** Ultima Avaliacao Em */
            ultima_avaliacao_em: string | null;
            automacao: components["schemas"]["AutomacaoResposta"];
            /**
             * Rastreia Falhas
             * @description Sempre False, e é sobre as COLETAS: nada registra falha por fonte. Fonte sem entrega recente pode estar quebrada OU apenas sem novidade, e o banco não distingue os dois. A execução do pipeline, essa sim, é rastreada em `automacao` — não confunda os dois escopos
             * @default false
             */
            rastreia_falhas: boolean;
        };
        /** SugestaoResposta */
        SugestaoResposta: {
            /** Ticker Objeto */
            ticker_objeto: string;
            /** Tipo Operacao */
            tipo_operacao: string;
            /** Codigo Opcao */
            codigo_opcao: string | null;
            /** Strike */
            strike: number | null;
            /** Vencimento */
            vencimento: string | null;
            /** Premio Estimado */
            premio_estimado: number | null;
            /** Status */
            status: string;
            /**
             * Criterios
             * @description Snapshot completo, com a base de valorização
             */
            criterios: {
                [key: string]: unknown;
            };
            /**
             * Pendente Revisao Humana
             * @description Sempre True: nenhuma sugestão é ordem executada
             */
            pendente_revisao_humana: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VelaResposta */
        VelaResposta: {
            /**
             * Abertura Em
             * Format: date-time
             * @description INÍCIO do período, não o momento da coleta
             */
            abertura_em: string;
            /** Abertura */
            abertura: number;
            /** Maxima */
            maxima: number;
            /** Minima */
            minima: number;
            /** Fechamento */
            fechamento: number;
            /** Volume */
            volume: number | null;
        };
        /** VigiarEntrada */
        VigiarEntrada: {
            /** Ticker */
            ticker: string;
            /**
             * Motivo
             * @description Por que este ticker entrou na watchlist — a pergunta que aparece meses depois, quando ninguém lembra
             */
            motivo?: string | null;
        };
        /**
         * WatchlistResposta
         * @description A watchlist e o custo que ela impõe.
         *
         *     O orçamento vem junto de propósito: vigiar não é de graça, e o número
         *     de vigiados é limitado por ele. Mostrar a lista sem mostrar o teto
         *     deixaria o usuário descobrir o limite quando a coleta da carteira
         *     falhasse no fim do dia.
         */
        WatchlistResposta: {
            /** Vigiados */
            vigiados: string[];
            /**
             * Universo
             * @description CARTEIRA ∪ VIGIADOS — o que os ETLs coletam e a varredura percorre
             */
            universo: string[];
            /**
             * Requests Por Ticker Dia
             * @description Cotação + duas janelas de vela + opções
             */
            requests_por_ticker_dia: number;
            /** Orcamento Diario */
            orcamento_diario: number;
            /**
             * Tickers Suportados
             * @description Teto de tickers no universo, dado o orçamento
             */
            tickers_suportados: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_ativos_ativos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtivoResposta"][];
                };
            };
        };
    };
    cadastrar_ativo_ativos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtivoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtivoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_posicoes_posicoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosicaoAbertaResposta"][];
                };
            };
        };
    };
    registrar_posicao_posicoes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosicaoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosicaoCriada"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    encerrar_posicao_posicoes__posicao_id__encerrar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                posicao_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncerramentoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResposta"];
                };
            };
        };
    };
    adicionar_a_watchlist_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VigiarEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_da_watchlist_watchlist__ticker__remover_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ler_caixa_caixa_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaixaResposta"];
                };
            };
        };
    };
    lancar_caixa_caixa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaixaEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_no_catalogo_catalogo_get: {
        parameters: {
            query: {
                busca: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoResposta"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cnpj_do_catalogo_catalogo__ticker__cnpj_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    carteira_carteira_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarteiraResposta"];
                };
            };
        };
    };
    cotacoes_cotacoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CotacaoResposta"][];
                };
            };
        };
    };
    sugestoes_sugestoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SugestaoResposta"][];
                };
            };
        };
    };
    desfecho_desfecho_get: {
        parameters: {
            query?: {
                data?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DesfechoResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resultados_resultados_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadosResposta"];
                };
            };
        };
    };
    saude_coleta_saude_coleta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaudeColetaResposta"];
                };
            };
        };
    };
    candles_candles_get: {
        parameters: {
            query: {
                ticker: string;
                intervalo?: string;
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResposta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operacoes_operacoes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperacoesResposta"];
                };
            };
        };
    };
    enriquecimento_enriquecimento_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnriquecimentoResposta"];
                };
            };
        };
    };
    parametros_parametros_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParametrosResposta"];
                };
            };
        };
    };
}
